name: My First Workflow

#trigger
on:
  push:
    branches:
      - releases/*

# Jobs in the workflow
jobs:
#job name
  my-first-workflow:
    #OS that this workflow will be running on
    runs-on: ubuntu-latest

    #list of steps to perform task
    steps: 
    - name: Checkout the  current repo
      uses: actions/checkout@v3
      with:
        branch: releases/*

    - name: List my current directory after Checkout
      run: ls -la

