name: Release and deploy Todo

#trigger
on:
  push:
    branches:
      - "release/[A-Za-Z0-9.]+"

# Jobs in the workflow
jobs:
#job name
  mrelease-and-deploy:
    #OS that this workflow will be running on
    runs-on: ubuntu-latest

    #list of steps to perform task
    steps: 
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the  current repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    - name: List my current directory after Checkout
      run: ls -la

